### ISSUE TITLE
charge finishing task can't be interrupted

### ISSUE THREAD

**Issue by aaronchongth** [osrf/fleet_adapter_mir#17]
During a charge finishing task, once the robot has completed docking and starts charging, the fleet adapter is unable to give new commands, even when the robot's charge is full.

This is probably due to a logic error in the command handle when the `dock` command is executed and how it checks to consider the docking completed.

**Comment by RBinsonB** [comment]
I also wanted to use this opportunity to look at what happen if the MiR docking missions is set to charge until a new mission is sent to the robot. In this case, the state stays on `Executing` (not `Ready`) even if the robot can technically receive new missions.

If the docking is reworked, it could be thought to include this case as well.

**Comment by RBinsonB** [comment]
Opened a PR to fix the issue of the charging not finishing: 
* https://github.com/osrf/fleet_adapter_mir/pull/31
