### ISSUE TITLE
Allow the user to override the initial waypoints from the command line

### ISSUE THREAD

**Issue by mxgrey** [osrf/fleet_adapter_mir#5]
The config file allows the initial waypoints to be specified for the robots, but that means modifying the initial waypoints would require a change to source code. It would be convenient for users if they can instead specify the starting waypoints from the command line.

Note that the CLI arguments need to have a way to differentiate the initial waypoints of different robots for multi-robot setups.

We should also consider if maybe the initial waypoint specification should be removed from the config-file altogether. If that static information is incorrect, it could cause some significant problems and confusion for users.

**Comment by aaronchongth** [comment]
This is fixed now, as the initial waypoints are optional now.
