### ISSUE TITLE
It looks like the mission creation API is always being called

### ISSUE THREAD

**Issue by mxgrey** [osrf/fleet_adapter_mir#7]
From [this line of code](https://github.com/osrf/fleet_adapter_mir/blob/main/fleet_adapter_mir/fleet_adapter_mir.py#L519) it looks like the mission creation API is always being used, because (if I understand correctly) the `create_move_coordinate_mission` function will always be called before the dict lookup is performed.

**Comment by aaronchongth** [comment]
Closing via https://github.com/osrf/fleet_adapter_mir/pull/16
